Name - Gajal Garg  <br>
SAP ID - 500109972  <br>
Batch - 3

## Pandas

In [ ]:
import pandas as pd

# Load a CSV file into a DataFrame
df_csv = pd.read_csv('data1.csv')

In [ ]:
df_csv

S. NO             Name  SAP ID  Subject 1 Subject 2 Subject 3
0       1      Gazal Garg    9972         87        89        87
1       2  Vaidehi Laddha    9146         90        34        78
2       3    Sourabh Soni    9472         86        78        43
3       4     Eroze Barua    9528         43       NAN        90
4       5  Kanhaiya Sethi    9966         94        78       NAN

In [ ]:
print(df_csv.shape)

(5, 6)


In [ ]:
print(df_csv.columns)

Index(['S. NO ', 'Name', 'SAP ID', 'Subject 1', 'Subject 2', 'Subject 3'], dtype='object')


In [ ]:
# Display the first 2 rows
print(df_csv.head(2))

# Display the last 2 rows
print(df_csv.tail(2))

   S. NO             Name  SAP ID  Subject 1 Subject 2 Subject 3
0       1      Gazal Garg    9972         87        89        87
1       2  Vaidehi Laddha    9146         90        34        78
   S. NO             Name  SAP ID  Subject 1 Subject 2 Subject 3
3       4     Eroze Barua    9528         43       NAN        90
4       5  Kanhaiya Sethi    9966         94        78       NAN


In [ ]:
print(df_csv.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   S. NO      5 non-null      int64 
 1   Name       5 non-null      object
 2   SAP ID     5 non-null      int64 
 3   Subject 1  5 non-null      int64 
 4   Subject 2  5 non-null      object
 5   Subject 3  5 non-null      object
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes
None


In [ ]:
print(df_csv.describe())

         S. NO        SAP ID  Subject 1
count  5.000000     5.000000   5.000000
mean   3.000000  9616.800000  80.000000
std    1.581139   353.062601  20.916501
min    1.000000  9146.000000  43.000000
25%    2.000000  9472.000000  86.000000
50%    3.000000  9528.000000  87.000000
75%    4.000000  9966.000000  90.000000
max    5.000000  9972.000000  94.000000


In [ ]:
column_a = df_csv['Subject 1']
selected_columns = df_csv[['Subject 1', 'Subject 2']]
column_a

0    87
1    90
2    86
3    43
4    94
Name: Subject 1, dtype: int64

In [ ]:
selected_columns

Subject 1 Subject 2
0         87        89
1         90        34
2         86        78
3         43       NAN
4         94        78

In [ ]:
first_three_rows = df_csv[:3]
row_by_label = df_csv.iloc[3]

In [ ]:
first_three_rows

S. NO             Name  SAP ID  Subject 1 Subject 2 Subject 3
0       1      Gazal Garg    9972         87        89        87
1       2  Vaidehi Laddha    9146         90        34        78
2       3    Sourabh Soni    9472         86        78        43

In [ ]:
row_by_label

S. NO                  4
Name         Eroze Barua
SAP ID              9528
Subject 1             43
Subject 2            NAN
Subject 3             90
Name: 3, dtype: object

# Numpy

In [ ]:
# Array Creation and Manipulation

import numpy as np

arr_1D = np.array(10)
print(arr_1D)

list1 = [1,2,3,5,6]
list2 = [5,7,8,3,2]
list3 = [4,7,9,3,9]

arr_2D = np.array([list1 , list2])
print(arr_2D)
arr_3D = np.array([list1, list2, list3])
print(arr_3D)

# using np.arange
arr = np.arange(15)
print(arr)

10
[[1 2 3 5 6]
 [5 7 8 3 2]]
[[1 2 3 5 6]
 [5 7 8 3 2]
 [4 7 9 3 9]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
# Performing basic operations on arrays (indexing, slicing, reshaping, concatenation).

# Indexing
arr = np.array([1,3,4,5,7,8])
print(arr)
print(arr[3])

# Slicing
print(arr[2:4])
print(arr[::-1])

# Reshaping
arr2 = np.arange(10).reshape(2,5)
print(arr2)

# Concatenation
array1 =  np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

updated_array = np.concatenate((array1 , array2))
print(updated_array)

[1 3 4 5 7 8]
5
[4 5]
[8 7 5 4 3 1]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Shape
arr = np.array([[1,2,3,4] , [5,6,7,8] , [3,6,9,2]])
print(arr.shape)

# Size
print(arr.size)

# dtype
print(arr.dtype)

# ndim
print(arr.ndim)

(3, 4)
12
int64
2


In [ ]:
# Reshape
arr = np.arange(8)
print(arr)

new_array = arr.reshape(4,2)
print(new_array)

new_array2 = arr.reshape(2,4)
print(new_array2)

# Flatten
arr.flatten()
print(arr)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
